include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_escaping_inner_quotes
    - avoid_multiple_declarations_per_line
    - avoid_void_async
    - directives_ordering
    - prefer_single_quotes
    - sort_constructors_first